name: image-classification
functions:
- name: utils
  spec:
    kind: job
    metadata:
      name: utils
      tag: ''
      hash: b3c6e09f037a657ee4ff484c4aec626d19c8b1ac
      project: image-classification
      categories: []
    spec:
      command: ''
      args: []
      image: mlrun/ml-models:0.4.6
      env:
      - name: V3IO_API
        value: ''
      - name: V3IO_USERNAME
        value: ''
      - name: V3IO_ACCESS_KEY
        value: ''
      default_handler: ''
      description: ''
      build:
        functionSourceCode: IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlciBvbiAyMDIwLTA0LTI2IDEyOjM3CgppbXBvcnQgb3MKaW1wb3J0IHppcGZpbGUKaW1wb3J0IGpzb24KZnJvbSB0ZW1wZmlsZSBpbXBvcnQgbWt0ZW1wCmltcG9ydCBwYW5kYXMgYXMgcGQKCmRlZiBvcGVuX2FyY2hpdmUoY29udGV4dCwgCiAgICAgICAgICAgICAgICAgdGFyZ2V0X2Rpcj0nY29udGVudCcsCiAgICAgICAgICAgICAgICAgYXJjaGl2ZV91cmw9JycsCiAgICAgICAgICAgICAgICAgcmVmcmVzaD1GYWxzZSk6CiAgICAiIiJPcGVuIGEgZmlsZS9vYmplY3QgYXJjaGl2ZSBpbnRvIGEgdGFyZ2V0IGRpcmVjdG9yeQogICAgCiAgICBub3RlOiBpZiBgcmVmcmVzaGAgaXMgVHJ1ZSB0aGUgY29udGVudCB3aWxsIGJlIHJlLWRvd25sb2FkZWQKICAgICIiIgogICAgaWYgbm90IG9zLnBhdGguaXNkaXIodGFyZ2V0X2Rpcikgb3IgcmVmcmVzaCBpcyBUcnVlOgogICAgICAgIG9zLm1ha2VkaXJzKHRhcmdldF9kaXIsIGV4aXN0X29rPVRydWUpCiAgICAgICAgY29udGV4dC5sb2dnZXIuaW5mbygnVmVyaWZpZWQgZGlyZWN0b3JpZXMnKQoKICAgICAgICBjb250ZXh0LmxvZ2dlci5pbmZvKCdFeHRyYWN0aW5nIHppcCcpCiAgICAgICAgemlwX3JlZiA9IHppcGZpbGUuWmlwRmlsZShhcmNoaXZlX3VybCwgJ3InKQogICAgICAgIHppcF9yZWYuZXh0cmFjdGFsbCh0YXJnZXRfZGlyKQogICAgICAgIHppcF9yZWYuY2xvc2UoKQoKICAgICAgICBjb250ZXh0LmxvZ2dlci5pbmZvKGYnZXh0cmFjdGVkIGFyY2hpdmUgdG8ge3RhcmdldF9kaXJ9JykKICAgIGNvbnRleHQubG9nX2FydGlmYWN0KCdjb250ZW50JywgbG9jYWxfcGF0aD10YXJnZXRfZGlyKQoKZGVmIGNhdGVnb3JpZXNfbWFwX2J1aWxkZXIoY29udGV4dCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgc291cmNlX2RpciwKICAgICAgICAgICAgICAgICAgICAgICAgICAgZGZfZmlsZW5hbWU9J2ZpbGVfY2F0ZWdvcmllc19kZi5jc3YnLAogICAgICAgICAgICAgICAgICAgICAgICAgICBtYXBfZmlsZW5hbWU9J2NhdGVnb3JpZXNfbWFwLmpzb24nKToKICAgICIiIlJlYWQgbGFiZWxlZCBpbWFnZXMgZnJvbSBhIGRpcmVjdG9yeSBhbmQgY3JlYXRlIGNhdGVnb3J5IG1hcCArIGRmCiAgICAKICAgIGZpbGVuYW1lIGZvcm1hdDogPGNhdGVnb3J5Pi5OTi5qcGciIiIKICAgIAogICAgZmlsZW5hbWVzID0gW2ZpbGUgZm9yIGZpbGUgaW4gb3MubGlzdGRpcihzb3VyY2VfZGlyKSBpZiBmaWxlLmVuZHN3aXRoKCcuanBnJyldCiAgICBjYXRlZ29yaWVzID0gW10KICAgICAgICAKICAgIGZvciBmaWxlbmFtZSBpbiBmaWxlbmFtZXM6CiAgICAgICAgY2F0ZWdvcnkgPSBmaWxlbmFtZS5zcGxpdCgnLicpWzBdCiAgICAgICAgY2F0ZWdvcmllcy5hcHBlbmQoY2F0ZWdvcnkpCgogICAgZGYgPSBwZC5EYXRhRnJhbWUoewogICAgICAgICdmaWxlbmFtZSc6IGZpbGVuYW1lcywKICAgICAgICAnY2F0ZWdvcnknOiBjYXRlZ29yaWVzCiAgICB9KQogICAgZGZbJ2NhdGVnb3J5J10gPSBkZlsnY2F0ZWdvcnknXS5hc3R5cGUoJ3N0cicpCiAgICAKICAgIGNhdGVnb3JpZXMgPSBkZi5jYXRlZ29yeS51bmlxdWUoKQogICAgY2F0ZWdvcmllcyA9IHtpOiBjYXRlZ29yeSBmb3IgaSwgY2F0ZWdvcnkgaW4gZW51bWVyYXRlKGNhdGVnb3JpZXMpfQogICAgd2l0aCBvcGVuKG9zLnBhdGguam9pbihjb250ZXh0LmFydGlmYWN0X3BhdGgsIG1hcF9maWxlbmFtZSksICd3JykgYXMgZjoKICAgICAgICBmLndyaXRlKGpzb24uZHVtcHMoY2F0ZWdvcmllcykpCiAgICAgICAgCiAgICBjb250ZXh0LmxvZ2dlci5pbmZvKGNhdGVnb3JpZXMpCiAgICBjb250ZXh0LmxvZ19hcnRpZmFjdCgnY2F0ZWdvcmllc19tYXAnLCBsb2NhbF9wYXRoPW1hcF9maWxlbmFtZSkKICAgIGNvbnRleHQubG9nX2RhdGFzZXQoJ2ZpbGVfY2F0ZWdvcmllcycsIGRmPWRmLCBsb2NhbF9wYXRoPWRmX2ZpbGVuYW1lKQoK
        commands: []
        code_origin: https://github.com/yjb-ds/demos.git#a7b063bf94a0853a9ebc7e6c8e1abc0dfa6ab1f3
- name: trainer
  spec:
    kind: mpijob
    metadata:
      name: trainer
      project: image-classification
      categories: []
    spec:
      command: /User/repos/demos/horovod-pipe/src/horovod-training.py
      args: []
      image: mlrun/ml-models:0.4.6
      env: []
      description: ''
      replicas: 4
      image_pull_policy: Always
      build:
        commands: []
- url: hub://tf2_serving
  name: serving
workflows:
- name: main
  path: src/workflow.py
artifacts:
- key: images
  kind: ''
  iter: 0
  tree: latest
  target_path: http://iguazio-sample-data.s3.amazonaws.com/catsndogs.zip
  db_key: images
