# Generated by nuclio.export.NuclioExporter on 2019-11-20 12:17

import v3io_frames as v3f
from datetime import datetime, timedelta
import os
# importing shutil module
import shutil

def handler(context, event):
    kv_table_path = 'iguazio/demos/face-recognition/artifacts/encodings'
    user_name = 'iguazio'
    password = 'datal@ke!'
    client = v3f.Client("framesd:8081", user=user_name, password=password , container="users")
    df = client.read(backend='kv', table=kv_table_path, reset_index=True)
    context.logger.info(df.head())
    df2 = df[['fileName', 'camera', 'label', 'imgUrl']]
    options = ['unknown']
    df3 = df2[df2.fileName.str.startswith(tuple(options))]
    for idx in range(len(df3)):
        img_url = df3.iloc[idx]['imgUrl']
        splited = img_url.split("/")
        destination = "/".join((splited[0],splited[1],splited[2],splited[3],"dataset/label_pending"))
        print(img_url)
        print(idx)
        print(splited)
        print(destination)
        # Move the content of
        # source to destination

        dest = shutil.move(img_url, destination)
