FROM python:3.7

EXPOSE 8501
RUN pip install streamlit 
RUN pip install opencv-contrib-python imutils pandas matplotlib v3io-frames

RUN mkdir -p /root/.streamlit/
RUN echo '[general]\nemail = "a@a.a"' > /root/.streamlit/credentials.toml
RUN echo '[browser]\ngatherUsageStats = false' > /root/.streamlit/config.toml






