FROM python:3.7

EXPOSE 8501
RUN pip install streamlit 
RUN pip install  opencv-contrib-python imutils pandas matplotlib v3io_frames==0.7.37

RUN mkdir -p /root/.streamlit/
RUN echo '[general]\nemail = "a@a.a"' > /root/.streamlit/credentials.toml
RUN echo '[browser]\ngatherUsageStats = false' > /root/.streamlit/config.toml
RUN echo '[server]\nenableCORS = false' >> /root/.streamlit/config.toml






